package com.goldenideabox.patents.model;

import java.io.Serializable;

public class Document implements Serializable {

    public interface DocumentParseStatus {
        /**
         * 初始化
         */
        public int INIT = 0;

        /**
         * 解析完成
         */
        public int PARSED = 1;
    }

    public interface DocumentSearchStatus {
        /**
         * 初始化
         */
        public int INIT = 0;

        /**
         * 查询完成
         */
        public int SEARCHED = 1;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.parseStatus
     *
     * @mbg.generated
     */
    private Integer parsestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.searchStatus
     *
     * @mbg.generated
     */
    private Integer searchstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table document
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.id
     *
     * @return the value of document.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.id
     *
     * @param id the value for document.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.name
     *
     * @return the value of document.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.name
     *
     * @param name the value for document.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.path
     *
     * @return the value of document.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.path
     *
     * @param path the value for document.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.type
     *
     * @return the value of document.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.type
     *
     * @param type the value for document.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.parseStatus
     *
     * @return the value of document.parseStatus
     *
     * @mbg.generated
     */
    public Integer getParsestatus() {
        return parsestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.parseStatus
     *
     * @param parsestatus the value for document.parseStatus
     *
     * @mbg.generated
     */
    public void setParsestatus(Integer parsestatus) {
        this.parsestatus = parsestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.searchStatus
     *
     * @return the value of document.searchStatus
     *
     * @mbg.generated
     */
    public Integer getSearchstatus() {
        return searchstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.searchStatus
     *
     * @param searchstatus the value for document.searchStatus
     *
     * @mbg.generated
     */
    public void setSearchstatus(Integer searchstatus) {
        this.searchstatus = searchstatus;
    }
}