package com.goldenideabox.patents.model;

import java.io.Serializable;

public class GooglePatent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.query_id
     *
     * @mbg.generated
     */
    private Integer queryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.publication_number
     *
     * @mbg.generated
     */
    private String publicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.also_published_number
     *
     * @mbg.generated
     */
    private String alsoPublishedNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.assignee_current
     *
     * @mbg.generated
     */
    private String assigneeCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.assignee_original
     *
     * @mbg.generated
     */
    private String assigneeOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.inventors
     *
     * @mbg.generated
     */
    private String inventors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.priority_date
     *
     * @mbg.generated
     */
    private String priorityDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.filing_date
     *
     * @mbg.generated
     */
    private String filingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.publications
     *
     * @mbg.generated
     */
    private String publications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.cited_by
     *
     * @mbg.generated
     */
    private Integer citedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.claims
     *
     * @mbg.generated
     */
    private Integer claims;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.classifications
     *
     * @mbg.generated
     */
    private String classifications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.pdf
     *
     * @mbg.generated
     */
    private String pdf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column google_patent.query_key
     *
     * @mbg.generated
     */
    private String queryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table google_patent
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.id
     *
     * @return the value of google_patent.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.id
     *
     * @param id the value for google_patent.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.query_id
     *
     * @return the value of google_patent.query_id
     *
     * @mbg.generated
     */
    public Integer getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.query_id
     *
     * @param queryId the value for google_patent.query_id
     *
     * @mbg.generated
     */
    public void setQueryId(Integer queryId) {
        this.queryId = queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.title
     *
     * @return the value of google_patent.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.title
     *
     * @param title the value for google_patent.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.publication_number
     *
     * @return the value of google_patent.publication_number
     *
     * @mbg.generated
     */
    public String getPublicationNumber() {
        return publicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.publication_number
     *
     * @param publicationNumber the value for google_patent.publication_number
     *
     * @mbg.generated
     */
    public void setPublicationNumber(String publicationNumber) {
        this.publicationNumber = publicationNumber == null ? null : publicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.application_number
     *
     * @return the value of google_patent.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.application_number
     *
     * @param applicationNumber the value for google_patent.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber == null ? null : applicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.also_published_number
     *
     * @return the value of google_patent.also_published_number
     *
     * @mbg.generated
     */
    public String getAlsoPublishedNumber() {
        return alsoPublishedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.also_published_number
     *
     * @param alsoPublishedNumber the value for google_patent.also_published_number
     *
     * @mbg.generated
     */
    public void setAlsoPublishedNumber(String alsoPublishedNumber) {
        this.alsoPublishedNumber = alsoPublishedNumber == null ? null : alsoPublishedNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.assignee_current
     *
     * @return the value of google_patent.assignee_current
     *
     * @mbg.generated
     */
    public String getAssigneeCurrent() {
        return assigneeCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.assignee_current
     *
     * @param assigneeCurrent the value for google_patent.assignee_current
     *
     * @mbg.generated
     */
    public void setAssigneeCurrent(String assigneeCurrent) {
        this.assigneeCurrent = assigneeCurrent == null ? null : assigneeCurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.assignee_original
     *
     * @return the value of google_patent.assignee_original
     *
     * @mbg.generated
     */
    public String getAssigneeOriginal() {
        return assigneeOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.assignee_original
     *
     * @param assigneeOriginal the value for google_patent.assignee_original
     *
     * @mbg.generated
     */
    public void setAssigneeOriginal(String assigneeOriginal) {
        this.assigneeOriginal = assigneeOriginal == null ? null : assigneeOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.inventors
     *
     * @return the value of google_patent.inventors
     *
     * @mbg.generated
     */
    public String getInventors() {
        return inventors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.inventors
     *
     * @param inventors the value for google_patent.inventors
     *
     * @mbg.generated
     */
    public void setInventors(String inventors) {
        this.inventors = inventors == null ? null : inventors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.priority_date
     *
     * @return the value of google_patent.priority_date
     *
     * @mbg.generated
     */
    public String getPriorityDate() {
        return priorityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.priority_date
     *
     * @param priorityDate the value for google_patent.priority_date
     *
     * @mbg.generated
     */
    public void setPriorityDate(String priorityDate) {
        this.priorityDate = priorityDate == null ? null : priorityDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.filing_date
     *
     * @return the value of google_patent.filing_date
     *
     * @mbg.generated
     */
    public String getFilingDate() {
        return filingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.filing_date
     *
     * @param filingDate the value for google_patent.filing_date
     *
     * @mbg.generated
     */
    public void setFilingDate(String filingDate) {
        this.filingDate = filingDate == null ? null : filingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.publications
     *
     * @return the value of google_patent.publications
     *
     * @mbg.generated
     */
    public String getPublications() {
        return publications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.publications
     *
     * @param publications the value for google_patent.publications
     *
     * @mbg.generated
     */
    public void setPublications(String publications) {
        this.publications = publications == null ? null : publications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.cited_by
     *
     * @return the value of google_patent.cited_by
     *
     * @mbg.generated
     */
    public Integer getCitedBy() {
        return citedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.cited_by
     *
     * @param citedBy the value for google_patent.cited_by
     *
     * @mbg.generated
     */
    public void setCitedBy(Integer citedBy) {
        this.citedBy = citedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.claims
     *
     * @return the value of google_patent.claims
     *
     * @mbg.generated
     */
    public Integer getClaims() {
        return claims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.claims
     *
     * @param claims the value for google_patent.claims
     *
     * @mbg.generated
     */
    public void setClaims(Integer claims) {
        this.claims = claims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.classifications
     *
     * @return the value of google_patent.classifications
     *
     * @mbg.generated
     */
    public String getClassifications() {
        return classifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.classifications
     *
     * @param classifications the value for google_patent.classifications
     *
     * @mbg.generated
     */
    public void setClassifications(String classifications) {
        this.classifications = classifications == null ? null : classifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.summary
     *
     * @return the value of google_patent.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.summary
     *
     * @param summary the value for google_patent.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.pdf
     *
     * @return the value of google_patent.pdf
     *
     * @mbg.generated
     */
    public String getPdf() {
        return pdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.pdf
     *
     * @param pdf the value for google_patent.pdf
     *
     * @mbg.generated
     */
    public void setPdf(String pdf) {
        this.pdf = pdf == null ? null : pdf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column google_patent.query_key
     *
     * @return the value of google_patent.query_key
     *
     * @mbg.generated
     */
    public String getQueryKey() {
        return queryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column google_patent.query_key
     *
     * @param queryKey the value for google_patent.query_key
     *
     * @mbg.generated
     */
    public void setQueryKey(String queryKey) {
        this.queryKey = queryKey == null ? null : queryKey.trim();
    }
}