package com.goldenideabox.patents.model;

import java.io.Serializable;

public class QueryHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column query_history.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column query_history.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column query_history.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column query_history.query_key
     *
     * @mbg.generated
     */
    private String queryKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column query_history.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table query_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column query_history.id
     *
     * @return the value of query_history.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column query_history.id
     *
     * @param id the value for query_history.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column query_history.name
     *
     * @return the value of query_history.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column query_history.name
     *
     * @param name the value for query_history.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column query_history.type
     *
     * @return the value of query_history.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column query_history.type
     *
     * @param type the value for query_history.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column query_history.query_key
     *
     * @return the value of query_history.query_key
     *
     * @mbg.generated
     */
    public String getQueryKey() {
        return queryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column query_history.query_key
     *
     * @param queryKey the value for query_history.query_key
     *
     * @mbg.generated
     */
    public void setQueryKey(String queryKey) {
        this.queryKey = queryKey == null ? null : queryKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column query_history.status
     *
     * @return the value of query_history.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column query_history.status
     *
     * @param status the value for query_history.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}