package com.goldenideabox.patents.dao;


import com.goldenideabox.patents.model.DocumentKeywordFrequency;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentKeywordFrequencyMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_keyword_frequency
     *
     * @mbg.generated
     */
    int insert(DocumentKeywordFrequency record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_keyword_frequency
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DocumentKeywordFrequency record);



    List<DocumentKeywordFrequency> getAllDocumentKeywordFrequency();

    List<String> getDocumentWord(@Param("documentId")Integer documentId, @Param("count")Integer count);
}