package com.goldenideabox.patents.dao;

import com.goldenideabox.patents.model.QueryHistory;
import java.util.List;

public interface QueryHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query_history
     *
     * @mbg.generated
     */
    int insert(QueryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query_history
     *
     * @mbg.generated
     */
    int insertSelective(QueryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query_history
     *
     * @mbg.generated
     */
    QueryHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QueryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QueryHistory record);

    List<QueryHistory> getAllQueryHistory();
}